### ISSUE TITLE
Can't copy text from question into input - Code Compile Question Type 

### ISSUE THREAD

**Issue by alexandrumarinescu90** [SafeExamBrowser/seb-testing#3]
You can't do this in SEB 2.3 (beta): https://www.screencast.com/t/TLsHDNBbm
I checked in 2.2.3 and it worked ok.

**Comment by danschlet** [comment]
Please don't use screencast.com, as it still uses Flash to play video recordings. The Flash plugin is a absolute no-go in 2019 and we are boycotting any website like screencast.com which didn't realize that and is too lazy to implement playing videos using HTML5 features instead of the security disaster called Flash!

**Comment by alexandrumarinescu90** [comment]
@danschlet 
Added a new attachment: 
[Recording001.zip](https://github.com/SafeExamBrowser/seb-testing/files/3232062/Recording001.zip)

**Comment by danschlet** [comment]
SEB 2.3 has the new private clipboard feature (which can also be switched off (Config Tool/Security tab/Use private clipboard) when working with permitted third party applications and copy-paste between SEB browser and those apps is needed).

I guess the private clipboard doesn't work in this case. As you are working for one of our [SEB Consortium Gold Members](https://safeexambrowser.org/consortium/fees.html), can you create an issue in your internal JIRA and add me and dbuechel?Please set up a demo exam, so we can test it ourselves.
